##########################
# Computation Parameters #
##########################
# The number of beam angles for mutual
# information computation.
num_beams: 600
# The number of beams angles used to
# condition the map at a single point.
condition_steps: 50000
# The standard deviation of the sensor noise.
# If the noise dev is <= 0 the barely distorted
# computation will be used.
noise_dev: 0 # Meters
# The number of standard deviations before the
# noise is truncated.
noise_truncation: 4 # Std Deviations
# An integration step for the sensor noise
noise_integration_step: 0.25 # Meters

##############
# I/O Topics #
##############
# The map input (occupancy grid)
map_topic: "/map"
# map_topic: "/ridgeback/rtabmap/grid_map"
# The mutual surface output (MIGrid, see .msg file)
mi_topic: "/mi"

#################
# Visualization #
#################
# Publish a mutual information surface to
# RVIZ once it is computed
visualize: true
# Publish incomplete mutual information surfaces to
# RVIZ as they are being computed
visualize_more: true
# Visualize mutual information surfaces
mi_map_topic: "/mi_map"
# Visualize the map of conditional probabilities.
conditional_map_topic: "/conditional_map"
# Click on the map to condition a point
click_condition_topic: "/clicked_point"
# Visualize a randomized map for monte carlo compuation.
binary_map_topic: "/binary_map"
